### ISSUE TITLE
replace external images by internal images

### ISSUE THREAD

**Issue by bertux** [minaz-io/dashboard#1]
@farnam1997 to avoid potential future bugs the links using external images should use the same images but by pushing them in this repository.

**Comment by bertux** [comment]
made by farnam at https://github.com/farnam1997/dashboard/tree/farnam

**Comment by katesroad** [comment]
Got the message, I will replace the external images with internal ones.

**Comment by katesroad** [comment]
I closed it because we shipped this ticket
