### ISSUE TITLE
make frontend development for the rich history data collection based on figma

### ISSUE THREAD

**Issue by Tracifier** [minaz-io/dashboard#6]

**Comment by katesroad** [comment]
@minazb2b  Got the ticket, will finish it on **May 10(NYC time)**.

**Comment by minazb2b** [comment]
@katesroad got it. Thank you very much. All good :)

**Comment by katesroad** [comment]
@bertux  Do you idea which API endpoint should I query?

**Comment by bertux** [comment]
@katesroad There are not fully ready yet. I will let you know here as soon as they will work.

**Comment by bertux** [comment]
now Rich History DB connection is documented at https://github.com/minaz-io/knowledge_base/blob/bertux-db/DB.md but I will continue by using Oracle Analytics Cloud or Oracle Data Visualization Cloud Service, to access the rich history database and create analytics reports or data visualizations.
